export const metadata = {
  title: 'Terms of Service - GrooveSzn AutoPoster',
  description: 'Terms of Service for GrooveSzn AutoPoster',
}

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 to-white py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-4xl mx-auto bg-white rounded-xl shadow-lg p-8 md:p-12">
        <h1 className="text-4xl font-bold text-gray-800 mb-8">Terms of Service</h1>
        
        <div className="prose prose-lg max-w-none space-y-6 text-gray-700">
          <section>
            <h2 className="text-2xl font-semibold text-gray-800 mt-8 mb-4">1. Acceptance of Terms</h2>
            <p>
              Welcome to GrooveSzn AutoPoster. By accessing and using our service, you agree to be bound by these Terms of Service. If you do not agree with any part of these terms, you must not use our service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-800 mt-8 mb-4">2. Service Description</h2>
            <p>
              GrooveSzn AutoPoster is an AI-powered tool designed to automate the creation and distribution of short-form video content from YouTube to various social media platforms including TikTok, Instagram, YouTube Shorts, and Facebook.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-800 mt-8 mb-4">3. User Responsibilities</h2>
            <ul className="list-disc list-inside space-y-2 ml-4">
              <li>You are responsible for ensuring that you have the necessary rights and permissions to use any YouTube videos or content you submit to our service.</li>
              <li>You must comply with all applicable laws and regulations, including copyright and intellectual property laws, when using our service.</li>
              <li>You are responsible for maintaining the confidentiality of your API keys and access tokens for third-party services.</li>
              <li>You must not use our service to post content that violates platform terms of service, including but not limited to: spam, hate speech, illegal content, or content that infringes on others' rights.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-800 mt-8 mb-4">4. Intellectual Property</h2>
            <p>
              All content generated by our service (e.g., captions, clips) based on your input remains your intellectual property. We do not claim ownership over your content. However, by using our service, you grant us a license to process and distribute your content as necessary to provide the service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-800 mt-8 mb-4">5. Disclaimer of Warranties</h2>
            <p>
              Our service is provided "as is" without any warranties, express or implied. We do not guarantee that the service will be uninterrupted, error-free, or secure. We are not responsible for any content posted using our service, nor do we endorse any content created by users.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-800 mt-8 mb-4">6. Limitation of Liability</h2>
            <p>
              GrooveSzn AutoPoster shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of profits or revenues, whether incurred directly or indirectly, or any loss of data, use, goodwill, or other intangible losses, resulting from your use of or inability to use our service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-800 mt-8 mb-4">7. Changes to Terms</h2>
            <p>
              We reserve the right to modify these Terms at any time. We will notify you of any changes by posting the new Terms on this page. Your continued use of the service after such changes constitutes acceptance of the new Terms.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-800 mt-8 mb-4">8. Contact Information</h2>
            <p>
              If you have any questions about these Terms of Service, please contact us through our support channels.
            </p>
          </section>

          <div className="mt-12 pt-8 border-t border-gray-200">
            <p className="text-sm text-gray-500">
              <strong>Last updated:</strong> November 2, 2025
            </p>
          </div>
        </div>

        <div className="mt-8">
          <a
            href="/"
            className="inline-flex items-center px-6 py-3 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors"
          >
            ← Back to Dashboard
          </a>
        </div>
      </div>
    </div>
  )
}

